apiVersion: v1
kind: Service
metadata:
  name: dis-brands-svc
  namespace: shared-domain
  labels:
    app: dis-brands
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: dis-brands

